### ISSUE TITLE
Minified css breaks unicode symbols

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#390]
```css
smile:before {
  content: "\200B";
}
```
is converted to 
```css
smile:before {
  content: "200B";
}
```
in production.

**Comment by mgechev** [comment]
Thanks for reporting this out! Unfortunately it is not issue in the seed but in cssnano. Would you report it there?

**Comment by ben-eb** [comment]
I've tried this with v3.4.0 and I can't reproduce on the command line; the output is correct:

```css
smile:before{content:"\200B"}
```

Perhaps it is something else in your environment?
