### ISSUE TITLE
How to load fonts?

### ISSUE THREAD

**Issue by dchacke** [mgechev/angular2-seed#541]
I am using Font Awesome on my website. I installed it using npm and then added it to the list of files that needs to be injected in config.ts:

```
...
{ src: 'node_modules/font-awesome/css/font-awesome.css', inject: true, dest: CSS_DEST }
...
```

This works fine in development, but once I build the app and serve it with Node using Express, the fonts are not displayed. The following request is made, just like in dev, but responds with a 404:

node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.5.0

I have tried adding the font file itself to the list of files to be injected as well:

```
{ src: 'node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.5.0', inject: true, dest: CSS_DEST }
```

but to no avail.

What am I doing wrong? I am also wondering why it works in development but not in production?

Node version: v4.0.0
NPM version: 3.7.3

**Comment by RobinsonAndrew** [comment]
Hi. I'm using Font Awesome as well in my project. The issue is that the in the font-awesome css it tries to look in the fonts folder to get the fonts.

```css
@font-face {
  font-family: 'FontAwesome';
  src: url("../fonts/fontawesome-webfont.eot?v=4.5.0");
  src: url("../fonts/fontawesome-webfont.eot?#iefix&v=4.5.0") format("embedded-opentype"), url("../fonts/fontawesome-webfont.woff2?v=4.5.0") format("woff2"), url("../fonts/fontawesome-webfont.woff?v=4.5.0") format("woff"), url("../fonts/fontawesome-webfont.ttf?v=4.5.0") format("truetype"), url("../fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular") format("svg");
  font-weight: normal;
  font-style: normal; }
```
so if you are injecting the woff into the css folder then it won't work as it won't be looking there for that file. You could try make a fonts folder instead and inject into that. However I'm using a gulp task to build the fonts folder from the src:

```javascript
import {join} from 'path';
import {BOOTSTRAP_SRC, FONT_AWESOME_SRC} from '../config';
import {APP_DEST} from '../config';

export = function buildFonts(gulp, plugins) {
  return function () {
    return gulp.src([
        join(BOOTSTRAP_SRC, '**/*.eot'),
        join(BOOTSTRAP_SRC, '**/*.ijmap'),
        join(BOOTSTRAP_SRC, '**/*.ttf'),
        join(BOOTSTRAP_SRC, '**/*.woff'),
        join(BOOTSTRAP_SRC, '**/*.woff2'),
        join(FONT_AWESOME_SRC, '**/*.eot'),
        join(FONT_AWESOME_SRC, '**/*.ijmap'),
        join(FONT_AWESOME_SRC, '**/*.ttf'),
        join(FONT_AWESOME_SRC, '**/*.woff'),
        join(FONT_AWESOME_SRC, '**/*.woff2')
      ])
      .pipe(gulp.dest(APP_DEST));
  };
}
```


where I have defined FONT_AWESOME_SRC in my config.ts file in the tools folder as: 
```javascript
export const FONT_AWESOME_SRC     = 'node_modules/font-awesome/';
```
If you add this as build.fonts.ts in the tools/tasks folder and then in gulpfile.ts edit the 'build.prod' task to be like this  (I have also changed the 'build.dev' task) : 
```javascript
// Build prod.
gulp.task('build.prod', done =>
  runSequence('clean.prod',
              'tslint',
              'build.assets.prod',
              'build.fonts',
              'build.html_css.prod',
              'build.js.prod',
              'build.bundles',
              'build.bundles.app',
              'build.index.prod',
              done));
```

i.e. adding the 'build.fonts' task to the sequence. It should then build the fonts folder into the dist/prod folder. If that doesn't work then check where the css file is. Font-awesome is trying to look in '../fonts/' so the css file should be in a css folder which is on the same level as a fonts folder.

Hope that helps.
