### ISSUE TITLE
css animation in main.css overriden in prod.

### ISSUE THREAD

**Issue by danypellerin** [mgechev/angular2-seed#934]
If you declare an animation in the main.css file (src/client/css), it gets overriden if an animation is created in the css file of a component of the shared folder (and I guess any other component folder).

example in main.css:

```css
@keyframes vanish {
    0%   { opacity: 1; }
    100% { opacity: 0; }
}
```

example in home.component.css:

```css
@keyframes appear{
    0%   { opacity: 0; }
    100% { opacity: 1; }
}
```

Elements to which the vanish animation is applied will have the appear animation applied instead.

This only happens when using the BUILD.PROD script and this is due to the fact that the variables are renamed during the build. Both animations get named "a".

Manually renaming the animation in the compiled main.css (which becomes all.css) fixes the issue.
