### ISSUE TITLE
build.prod doesnt work??

### ISSUE THREAD

**Issue by lmessinger** [mgechev/angular2-seed#975]
Hi

on running **npm run build.prod** we're getting errors on files we added under app/components

```
NOENT: no such file or directory, open '/home/liorm/bkup/servo-admin/dist/tmp/app/components/typography/components/typography/typography.html'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: /home/liorm/bkup/servo-admin/dist/tmp/app/components/typography/components/typography/typography.html
    fileName: /home/liorm/bkup/servo-admin/dist/tmp/app/components/typography/typography.ts
```

any ideas?

thanks very much
Lior
